#ifndef KOALA_ASM_INFO_H
#define KOALA_ASM_INFO_H

#define KOALA_ASM_VERSION_MAJOR 0
#define KOALA_ASM_VERSION_MINOR 0
#define KOALA_ASM_VERSION_PATCH 0
#define KOALA_ASM_VERSION_IDENTIFIER ""

#endif